package connect4;

/**
 * Jafar.java created by eberg on Apr 3, 2014 at 1:08:37 PM
 */
public class Jafar extends javax.swing.JFrame {

    // Got rid of the declaration Japanel thePanel = new Japanel(this);
    // This at least kinda runs the game
    Japanel thePanel;

    public Jafar() {  // this constructor creates the form and displays it
        initComponents();
        setVisible(true);
        setBounds(100, 100, 700, 600);
        //add(thePanel = new Japanel(this));
        thePanel = new Japanel(this);
        add(thePanel);
        
    }

    /**
     * You can't modify the following code; it is regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        resetMenu = new javax.swing.JMenuItem();
        trainMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jMenu1.setText("File");

        resetMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        resetMenu.setText("Reset");
        resetMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMenuActionPerformed(evt);
            }
        });
        jMenu1.add(resetMenu);

        trainMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        trainMenuItem.setText("Train");
        trainMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(trainMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMenuActionPerformed
        thePanel.reset();
    }//GEN-LAST:event_resetMenuActionPerformed

    private void trainMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainMenuItemActionPerformed
        thePanel.train();

    }//GEN-LAST:event_trainMenuItemActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem resetMenu;
    private javax.swing.JMenuItem trainMenuItem;
    // End of variables declaration//GEN-END:variables

    void reset() {
        thePanel.reset();
    }
}
