/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package connect4;

import java.awt.Graphics;

/**
 *
 * @author eberg
 */
public class Japanel extends javax.swing.JPanel {

     Board theBoard;
     Jafar theFrame;

    /**
     * Creates new form Japanel
     */
     
     Japanel(Jafar f) {
        theFrame = f;
        initComponents();
        reset();
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        theBoard.paint(g, this.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (theBoard.isGameOver()) {
            return;
        }
        theBoard.released(evt.getX(), evt.getY());
        //System.out.println("fails" + theBoard.toString());
        repaint();

    }//GEN-LAST:event_formMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void reset() {
        if (theBoard != null) {
            System.out.println("new board");
            theBoard.stop();
        }
        theBoard = new Board();
        theBoard.setTheFrame(theFrame);
        //theBoard.setThePanel(this);
        theBoard.start();
        repaint();
        //System.out.println(theBoard.toString());

    }

    void printBoard() {
        System.out.println(theBoard.toString());
    }

    void train() {
        theBoard.train();
    }
}
